dist: trusty
sudo: true
language: python
python:
    - "3.6"
install:
    - pip install --upgrade pip
    - pip install pipenv
    - pipenv install --system --skip-lock
before_script:
    - pipenv run python manage.py makemigrations
    - pipenv run python manage.py migrate
script:
    - pipenv run manage.py test
notifications:
    email: false
