# Generated by Django 2.1.5 on 2019-01-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_cartentry_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceuser',
            name='email',
            field=models.EmailField(max_length=80, unique=True),
        ),
    ]
