# Generated by Django 2.1.5 on 2019-01-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20190114_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartentry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
